# Generated by Django 5.1.6 on 2025-02-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customerorder'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='driver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
